name: 'Build: Log Monitoring Logback'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'log-monitoring-logback/**'

  pull_request:
    branches:
      - main
    paths:
      - 'log-monitoring-logback/**'

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./log-monitoring-logback
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ./log-monitoring-logback
          cache-read-only: false
          arguments: clean build --console=plain --scan
