name: 'Build: Log Monitoring Logback'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'log-monitoring-logback/**'

  pull_request:
    branches:
      - main
    paths:
      - 'log-monitoring-logback/**'

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        working-directory: ./log-monitoring-logback
        run: ./gradlew clean build --console=plain --scan



